### ISSUE TITLE
Type Autocompletion Failing

### ISSUE THREAD

**Issue by zolero** [WhatsApp/WhatsApp-Nodejs-SDK#2]
# Expected behavior
I think it's because the exports are not defined in the file ./build/index.d.ts, that is configured in package.json.
```json
"exports": {
    ".": {
      "types": "./build/index.d.ts",
      "default": "./build/index.js"
    },
    "./package.json": "./package.json"
  },
```
And these settings in tsconfig.json.

```json
"paths": {
	"@/*": ["src/types/*"]
},
```

# Current behavior
Type Completions are failing.

## Context
Please provide any other relevant information about your application or configuration.
* Operating system: Windows 11
* Node.js version: v18.12.0
* SDK version: 0.0.3-Alpha
* Cloud API version: v16

## Failure Logs
![image](https://user-images.githubusercontent.com/6997299/229757079-2e0960d9-8c4c-4480-b1b7-4e2e35913325.png)
![image](https://user-images.githubusercontent.com/6997299/229757559-3e687a7d-9185-4b1f-997e-5a3e5e1cb356.png)

**Comment by rashedtalukder** [comment]
Thanks for pointing this out. The declarations are not necessary in the transpiled ES6 code that's in the build directory. Since Typescript doesn't provide a good way to handling paths or aliases and babel ignores .d.ts files, there's no clean way to make this work at the moment. We will remove the ./build/**/*.d.ts files going forward in the next push.

I'll leave this open for the moment to gather feedback.
