### ISSUE TITLE
GA timelines

### ISSUE THREAD

**Issue by pakogzz** [WhatsApp/WhatsApp-Nodejs-SDK#31]
Hi @rashedtalukder, I am working for a large enterprise BSP and would love to switch our stack to this SDK to offload some of our maintenance. When can we expect it to go GA? We have tracked the development and it has seemed to have suddenly stopped.

Really great work btw, this is very clean and thought out. However, we need at least the webhooks feature to be fixed so it would be great if that can be prioritised.

**Comment by jstdk** [comment]
Hopefully this project has not fall victim to the Meta layoff cycles

**Comment by jstdk** [comment]
@pakogzz, in all honesty, I have built the whole integration natively with webhooks and Node, it is very douable and will save you another dependency or risk of an unmaintained package.

**Comment by dmitryvinn-fb** [comment]
We regret to inform our WhatsApp community members and partners that due to recent shifting priorities within our organization, we have made the difficult decision to pause development on this project. We understand the inconvenience and disappointment this may cause, and we sincerely apologize for any disruption to your plans.

While we are unable to proceed with the project at this time, we remain open to exploring alternative solutions and future collaborations on this project. We appreciate your understanding and cooperation during this time.
